site_name: WalledEval Documentation

theme:
    name: "material"

    features:
        - navigation.tabs
        - search.suggest
        - search.share

    # 404 page
    static_templates:
        - 404.html

    # Necessary for search to work properly
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/favicon.png
    icon:
        logo: material/robot

    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode

extra_css:
    - stylesheets/style.css

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:
          generic: true
    - attr_list
    - md_in_html
    - pymdownx.tabbed:
          alternate_style: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - "Set-Up":
        - Installation: setup/installation.md
    - "LLM":
        - Overview: llm/index.md
        - "LLM Types": llm/llm_types.md
        - "Input Types": llm/input_types.md
        - "HuggingFace LLM Support": llm/huggingface.md
        - "Other API Support": llm/other_api.md
        - "Supporting your own LLMs": llm/supporting_your_own.md

plugins:
    - search

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/walledai/walledeval
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/walled-ai/

copyright: Copyright &copy; 2024 Walled AI
